accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, UserList, ChangeProfileView, ChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/list', UserList.as_view(), name='profile_list'),

    path('<int:pk>/change/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
]

homework48/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]

webapp/urls.py
from django.urls import path

from webapp.views.itemcart import CartView, CartAddView, CartDeleteView
from webapp.views.order import OrderListView, OrderCreateView
from webapp.views.product import IndexView, ProductDetailView, ProductCreateView, ProductDeleteView, ProductUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='detail_view'),
    path('product/add/', ProductCreateView.as_view(), name='create_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),

    path('product/<int:pk>/cart/add/', CartAddView.as_view(), name='cart_add'),
    path('cart/', CartView.as_view(), name='cart_view'),
    path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='cart_delete'),

    path('order/', OrderListView.as_view(), name='orders'),
    path('order/create/', OrderCreateView.as_view(), name='order_create'),

]

webapp/models.py
from django.db import models

CATEGORY = [('other', 'Разное'), ('dairy', 'Молочные продукты'), ('fruit', 'Фрукты'), ('seafood', 'Морепродукты')]


# Create your models here.
class Product(models.Model):
    name_product = models.CharField(max_length=100, null=True, blank=False, verbose_name='Имя продукта')
    descr_product = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание товара')
    category = models.CharField(max_length=25, null=True, blank=False, choices=CATEGORY, default=CATEGORY[0][0],
                                verbose_name='Категория')
    remainder = models.PositiveIntegerField(verbose_name='Остаток')
    price = models.DecimalField(null=True, blank=True, max_digits=7, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return f'{self.id}.{self.name_product}:{self.category}'

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class ItemCart(models.Model):
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, blank=True, related_name='items_cart')
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.pk}. {self.product}:{self.quantity}'

    @property
    def product_sum(self):
        return self.product.price * self.quantity

    class Meta:
        db_table = 'itemcart'
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'


class OrderProduct(models.Model):
    order = models.ForeignKey('webapp.Order', on_delete=models.CASCADE)
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(verbose_name="Количество")


class Order(models.Model):
    products = models.ManyToManyField("webapp.Product", related_name='orders',
                                      verbose_name='Продукты', through=OrderProduct)
    user = models.CharField(max_length=30, blank=True, verbose_name='Покупатель')
    phone = models.CharField(max_length=30,  verbose_name='Телефон')
    address = models.CharField(max_length=30, verbose_name='Адрес')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

webapp/views/product.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models.functions import Lower
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView

from webapp.models import Product
from webapp.forms import ProductFrom, SearchForm


# Create your views here.
class IndexView(ListView):
    model = Product
    template_name = 'product/index.html'
    context_object_name = 'products'
    ordering = 'name_product'
    paginate_by = 5
    queryset = Product.objects.filter(remainder__gt=0)


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductFrom
    template_name = 'product/create.html'

    def get_success_url(self):
        return reverse('detail_view', kwargs={"pk": self.object.pk})


class ProductDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'webapp:detail_product'
    model = Product
    template_name = 'product/detail_view.html'
    context_object_name = "product"


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'webapp:update_product'
    form_class = ProductFrom
    template_name = 'product/update.html'
    model = Product
    context_object_name = 'product'

    def get_success_url(self):
        return reverse('detail_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'webapp:delete_product'
    template_name = 'product/delete.html'
    model = Product
    context_object_name = 'product'
    success_url = reverse_lazy('index')


class SearchView(ListView):
    model = Product
    form_class = SearchForm
    context_object_name = 'product'
    product = []

    def get_queryset(self):
        form = self.form_class(self.request.GET)
        if form.is_valid():
            return Product.objects.filter(name_product__icontains=form.cleaned_data['name_product'])
        return Product.objects.all()

templates/product/create.html
{% extends "base.html" %}
{% block title %} Создание продукта {% endblock %}
{% block content %}
    <h1>Создание продукта</h1>
    <form action=" " method="post">
        {% include "partial/form.html" with button_text="Создать" %}
        <a href="{% url "webapp:index" %}" class="btn btn-primary">Назад</a>
    </form>
    <br/>
{% endblock %}

templates/product/delete.html
{% extends "base.html" %}
{% block title %}Удаление{% endblock %}
{% block content %}

<form action=" " method="post">
    {% csrf_token %}
    <h2>Вы действительно хотите удалить {{ product.name_product }}?</h2>
    <button type="submit" class="btn btn-primary">ДА</button>
<a href="{% url "webapp:detail_view" product.pk %}" class="btn btn-primary">НЕТ</a>
</form>
{% endblock %}

templates/product/detail_view.html
{% extends "base.html" %}
{% block title %} Детальный просмотр{% endblock %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:create_product' %}">Создать продукт</a>
    </li>
{% endblock %}
{% block content %}
    <br>
    <div class="card text-center">
        <div class="card-header">
            Категория: {{ product.get_status_display }}
        </div>
        <div class="card-body">
            <h5 class="card-title"> Имя: {{ product.name_product|upper }}</h5>
            <p class="card-title"> Категория: {{ product.get_category_display }}</p>
            <p class="card-text"> Описание: {{ product.descr_product }}</p>
            <p class="card-text"> Цена: {{ product.price }}</p>
            <p class="card-text"> Остаток: {{ product.remainder }}</p>
            {% if perms.webapp.delete_product %}
                <a href="{% url 'webapp:delete_product' product.pk %}" class="btn btn-primary">Удалить</a>
            {% endif %}
            {% if perms.webapp.update_product %}
                <a href="{% url 'webapp:update_product' product.pk %}" class="btn btn-primary">Редактировать</a>
            {% endif %}
            <a href="{% url 'webapp:index' %}" class="btn btn-primary">Назад</a>
        </div>
    </div>
{% endblock %}

templates/product/index.html
{% extends "base.html" %}
{% block title %}Products{% endblock %}
{% load static %}
{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link menu-right" href="{% url "accounts:logout" %}">Выход</a>
        </li>
        <li class="menu-right nav-link">
            <p>Привет, <a href="{% url 'accounts:profile' request.user.pk %}"
                         style="text-decoration:none; color: red"> {{ user.username }}</a></p>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Вход</a>
        </li>
        <li class="nav-item">
            <a class="nav-link"
               href="{% url "accounts:registration" %}?next={{ request.get_full_path }}">Регистрация</a>
        </li>
    {% endif %}
    {% if perms.webapp.create_product %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:create_product' %}">Создать продукт</a>
    </li>
    {% endif %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:cart_view' %}">Корзина</a>
    </li>
{% endblock %}
{% block content %}
    {% include 'partial/simple_search.html' %}
    <h1>Продукты</h1>
    {% for product in  products %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                {% if perms.webapp.detail_product %}
                <a href="{% url "webapp:detail_view" product.pk %}" style="text-decoration: none;color: red"><h5
                        class="card-title">{{ product.name_product }}</h5></a>
                {% endif %}
                <p class="card-text" style="text-decoration:none; color: red">{{ product.name_product }} </p>
                <p class="card-text">{{ product.price }}</p>
                <p class="card-text">{{ product.get_category_display }}</p>
                <form action="{% url "webapp:cart_add" product.pk %}" method="post">
                    {% csrf_token %}
                    <input style="float: right" class="btn btn-danger" type="submit" value="Добавить в корзину"/>
                </form>
            </div>
        </div>
        <br>
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

templates/product/search.html
{% extends "base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Search by name "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Records  {{ total_results }} found {{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for product in results %}
            <div class="card bg-light mb-3" style="max-width: 25rem;">
                <div class="card-header">{{ product.name_product }} ({{ product.price }})<span
                        style="padding: 0px 40px;">&nbsp;</span>
                    <a href="{% url 'webapp:update_product' product.pk %}">Редактировать</a>
                    <a href="{% url 'webapp:delete_product' product.pk %}">Удалить</a></div>
                <div class="card-body">
                    <p class="card-text">{{ product.descr_product }}</p>
                </div>
            </div>
        {% empty %}
            <p>Нет результатов.</p>
        {% endfor %}
        </button><a href="{% url "product_search" %}" class="btn btn-primary">Искать снова</a></button>
        </button><a href="{% url "webapp:index" %}" class="btn btn-primary">Назад</a></button>
    {% else %}
        <h1>Search by name</h1>
        <form action=".." method="get">
            {{ form.as_p }}
            <input type="submit" value="Искать" class="btn btn-primary">
            </button><a href="{% url "webapp:index" %}" class="btn btn-primary">Назад</a></button>
        </form>
    {% endif %}
{% endblock %}

templates/product/update.html
{% extends "base.html" %}
{% block title %}Update Product{% endblock %}
{% block content %}
    <h1>Update Product</h1>
    <form method="post" action=" ">
        {% include "partial/form.html" with button_text="Edit" %}

        <a href="{% url "webapp:index" %}" class="btn btn-primary">НАЗАД</a>
    </form>
{% endblock %}