accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, UserList, ChangeProfileView, ChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/list', UserList.as_view(), name='profile_list'),

    path('<int:pk>/change/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
]

homework48/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]

webapp/urls.py
from django.urls import path

from webapp.views.itemcart import CartView, CartAddView, CartDeleteView
from webapp.views.order import OrderListView, OrderCreateView
from webapp.views.product import IndexView, ProductDetailView, ProductCreateView, ProductDeleteView, ProductUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='detail_view'),
    path('product/add/', ProductCreateView.as_view(), name='create_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),

    path('product/<int:pk>/cart/add/', CartAddView.as_view(), name='cart_add'),
    path('cart/', CartView.as_view(), name='cart_view'),
    path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='cart_delete'),

    path('order/', OrderListView.as_view(), name='orders'),
    path('order/create/', OrderCreateView.as_view(), name='order_create'),

]

accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE,
                                verbose_name='User', related_name='profile')
    avatar = models.ImageField(upload_to='avatars', null=True, blank=True, verbose_name='Avatar')
    about_user = models.CharField(max_length=200, null=True, blank=True, verbose_name='About user')
    git = models.URLField(null=True, blank=True, verbose_name='GIT')

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile

User = get_user_model()


class MyUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'password1', 'password2', 'email', 'first_name', 'last_name')

    def is_valid(self):
        super().is_valid()
        data = self.cleaned_data
        if not data.get('first_name'):
            self.add_error('first_name', 'First Name fields must be filled')
            return False
        return True


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
        labels = {'first_name': 'Name', 'last_name': 'Last Name'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'about_user', 'git']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="New password", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm password", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Old password", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('The old password is wrong!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from accounts.models import Profile


class RegisterView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


class ProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'profile.html'
    paginate_by = 5
    paginate_orphans = 0
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        paginator = Paginator(self.get_object().projects.all(),
                              self.paginate_by,
                              self.paginate_orphans)
        page_number = self.request.GET.get('page', 1)
        page_object = paginator.get_page(page_number)

        context = super().get_context_data(**kwargs)
        context['page_obj'] = page_object
        context['projects'] = page_object.object_list
        context['is_paginated'] = page_object.has_other_pages()
        return context


class UserList(PermissionRequiredMixin, ListView):
    model = get_user_model()
    context_object_name = 'users'
    template_name = 'profile_list.html'
    permission_required = 'accounts.view_profile'


class ChangeProfileView(PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = 'change_user.html'
    profile_form_class = ProfileChangeForm
    context_object_name = 'user_obj'

    def has_permission(self):
        return self.request.user.is_superuser or self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'profile_form' not in context:
            context['profile_form'] = self.profile_form_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        profile_form = self.profile_form_class(instance=self.object.profile,
                                               data=request.POST,
                                               files=request.FILES)
        if form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        # self.get_form()
        form.save()
        profile_form.save()
        return redirect('accounts:profile', self.object.pk)

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form, profile_form=profile_form))


class ChangePasswordView(PasswordChangeView):
    template_name = 'change_password.html'

    # def get_object(self, queryset=None):
    #     return self.request.user

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})
    #
    # def form_valid(self, form):
    #     result = super().form_valid(form)
    #     update_session_auth_hash(self.request, self.object)
    #     return result

accounts/templates/change_password.html
{% extends 'base.html' %}

{% block content %}
    <h5>Change password</h5>
    <form action=" " method="post">
        {% include "partial/form.html" with button_text="Change" %}
    </form>
    <br/>
{% endblock %}

accounts/templates/change_user.html
{% extends 'base.html' %}

{% block content %}
    <h5>Change profile</h5>
    <form action=" " method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with fields_only=True %}
        {% include "partial/form.html" with form=profile_form  button_text="Change" %}
    </form>
    <br/>
{% endblock %}

accounts/templates/login.html
{% extends "base.html" %}

{% block title %}Enter{% endblock %}
{% block content %}
        <br>
    <h1 class="text-center">Enter</h1>
    <br>
    <div class="text-center">
        <form action="" method="post" class="w-50 ms-auto me-auto">
            {% csrf_token %}
            {% if has_error %}
                <p class="text-danger">Invalid username or password.</p>
            {% endif %}
            <div class="form-group">
                <label for="username" class="form-label">Username:</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Password:</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <button class="mt-3 btn btn-outline-dark" type="submit">Enter</button>
        </form>
    </div>
{% endblock %}

accounts/templates/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}
{% block nav %}
    {% if user_obj == user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_profile' user_obj.pk %}">Change profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%  url 'accounts:change_password' %}"> Change password</a>
        </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card flex-row mt-3">
        <div class="card-body">
            {% if user_obj.profile.avatar %}
                <img src="{{ user_obj.profile.avatar.url }}" class="card-img- w-25" alt="user avatar">
            {% endif %}
            <h5 class="card-title">{{ user_obj.username|upper }}</h5>
            <br>
            <p class="card-subtitle mb-2 -muted">{{ user_obj.first_name }}</p>
            <p class="card-subtitle mb-2 -muted"> {{ user_obj.last_name }}</p>
            <p class="card-subtitle mb-2 -muted">{{ user_obj.profile.about_user }}</p>
            <p class="card-subtitle mb-2 -muted">{{ user_obj.email }}</p>
            <p class="card-subtitle mb-2 -muted"> {{ user_obj.profile.git }}</p>
        </div>
    </div>
    <h5 class="text-center clear">Projects user:</h5>
    {% include 'partial/project_list_partial.html' %}
{% endblock %}

accounts/templates/profile_list.html
{% extends "base.html" %}

{% block content %}

    {% for user in users %}
        <div class="card">
            <div class="card-body">
                <p><a href="{% url 'accounts:profile' user.pk %}" style=" text-decoration: none;">{{ user.username }}</a></p>
                <p>{{ user.first_name }}</p>
                <p>{{ user.last_name }}</p>
            </div>
        </div>
        <br>

    {% endfor %}
{% endblock %}

accounts/templates/registration.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}
{% block content %}
    <br>
    <h1 class="text-center">Registration</h1>
    <form method="post">
          {% include "partial/form.html" with button_text="Regist" %}
    </form>
{% endblock %}