homework48/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]

webapp/urls.py
from django.urls import path

from webapp.views.itemcart import CartView, CartAddView, CartDeleteView
from webapp.views.order import OrderListView, OrderCreateView
from webapp.views.product import IndexView, ProductDetailView, ProductCreateView, ProductDeleteView, ProductUpdateView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='detail_view'),
    path('product/add/', ProductCreateView.as_view(), name='create_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),

    path('product/<int:pk>/cart/add/', CartAddView.as_view(), name='cart_add'),
    path('cart/', CartView.as_view(), name='cart_view'),
    path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='cart_delete'),

    path('order/', OrderListView.as_view(), name='orders'),
    path('order/create/', OrderCreateView.as_view(), name='order_create'),

]

webapp/models.py
from django.db import models

CATEGORY = [('other', 'Разное'), ('dairy', 'Молочные продукты'), ('fruit', 'Фрукты'), ('seafood', 'Морепродукты')]


# Create your models here.
class Product(models.Model):
    name_product = models.CharField(max_length=100, null=True, blank=False, verbose_name='Имя продукта')
    descr_product = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание товара')
    category = models.CharField(max_length=25, null=True, blank=False, choices=CATEGORY, default=CATEGORY[0][0],
                                verbose_name='Категория')
    remainder = models.PositiveIntegerField(verbose_name='Остаток')
    price = models.DecimalField(null=True, blank=True, max_digits=7, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return f'{self.id}.{self.name_product}:{self.category}'

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class ItemCart(models.Model):
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, blank=True, related_name='items_cart')
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.pk}. {self.product}:{self.quantity}'

    @property
    def product_sum(self):
        return self.product.price * self.quantity

    class Meta:
        db_table = 'itemcart'
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'


class OrderProduct(models.Model):
    order = models.ForeignKey('webapp.Order', on_delete=models.CASCADE)
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(verbose_name="Количество")


class Order(models.Model):
    products = models.ManyToManyField("webapp.Product", related_name='orders',
                                      verbose_name='Продукты', through=OrderProduct)
    user = models.CharField(max_length=30, blank=True, verbose_name='Покупатель')
    phone = models.CharField(max_length=30,  verbose_name='Телефон')
    address = models.CharField(max_length=30, verbose_name='Адрес')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

webapp/views/itemcart.py
from urllib.request import Request
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView

from webapp.forms import OrderForm
from webapp.models import ItemCart, Product


class CartView(TemplateView):
    template_name = 'item_cart.html'

    def get_context_data(self, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        arr = []
        for item in ItemCart.objects.all():
            arr.append(item.product.price * item.quantity)
        context['items'] = ItemCart.objects.all()
        context['total'] = sum(arr)
        context['form'] = OrderForm()
        return context


class CartAddView(View):
    def post(self, *args, **kwargs):
        product = get_object_or_404(Product, id=kwargs.get('pk'))
        product_cart = ItemCart.objects.filter(product=product)
        if product_cart:
            cart = product_cart[0]
            reverse_in_stock = product.remainder - (cart.quantity + 1)
            if reverse_in_stock >= 0:
                cart.quantity += 1
                cart.save()
        else:
            new_cart = ItemCart()
            new_cart.product = product
            new_cart.quantity = 1
            new_cart.save()
        return redirect(reverse('webapp:index'))


class CartDeleteView(TemplateView):
    template_name = 'item_cart.html'

    def post(self, *args, **kwargs):
        product_id = kwargs.get('pk')
        product_cart = ItemCart.objects.filter(product_id=product_id)
        if product_cart:
            product_cart.delete()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:cart_view')

webapp/views/order.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView

from webapp.forms import OrderForm
from webapp.models import OrderProduct, Product, ItemCart


class OrderListView(ListView):
    model = OrderProduct
    context_object_name = 'order_products'
    template_name = 'orders.html'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by("-order__created_at")


class OrderCreateView(View):
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            cart = ItemCart.objects.all()
            for item in cart:
                product = Product.objects.get(pk=int(item.product_id))
                OrderProduct.objects.create(order=order, product_id=item.product_id, amount=item.quantity)
                product.remainder -= int(item.quantity)
                product.save()
            cart.delete()
        return redirect(reverse('index'))

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title> {% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
  <a class="navbar-brand" href="{% url "webapp:index" %}">Домой</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        {%  block nav %}
        {%  endblock %}
    </ul>
  </div>
    </div>
</nav>
<div class="container">
        {% block content %}
        {% endblock %}

</div>
</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>

templates/detail_view.html
{% extends "base.html" %}
{% block title %} Детальный просмотр{% endblock %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'create_product' %}">Создать продукт</a>
    </li>
{% endblock %}
{% block content %}
    <br>
    <div class="card text-center">
        <div class="card-header">
            Категория: {{ product.get_status_display }}
        </div>
        <div class="card-body">
            <h5 class="card-title"> Имя: {{ product.name_product|upper }}</h5>
            <p class="card-title"> Категория:{{ product.get_category_display }}</p>
            <p class="card-text"> Описание: {{ product.descr_product }}</p>
            <p class="card-text"> Цена: {{ product.price }}</p>
            <p class="card-text"> Остаток: {{ product.remainder }}</p>
            <a href="{% url 'delete_product' product.pk %}" class="btn btn-primary">Удалить</a>
            <a href="{% url 'update_product' product.pk %}" class="btn btn-primary">Редактировать</a>
            <a href="{% url 'index' %}" class="btn btn-primary">Назад</a>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Products{% endblock %}
{% load static %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'create_product' %}">Создать продукт</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'product_search' %}">Найти продукт</a>
    </li>
{% endblock %}
{% block content %}
    <h1>Продукты</h1>
    {% for product in  products %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <a href="{% url "detail_view" product.pk %}" style="text-decoration: none;color: red"><h5 class="card-title">{{ product.name_product }}</h5></a>
                <p class="card-text">{{ product.price }}</p>
                <p class="card-text">{{ product.get_category_display  }}</p>
            </div>
        </div>
        <br>
    {% endfor %}
{% endblock %}

templates/item_cart.html
{% extends "base.html" %}
{% block title %}Products{% endblock %}
{% load static %}
{% block nav %}
{% endblock %}
{% block content %}

    <div>

        <table class="table">
            <thead>
            <tr>
                <th scope="col">Название:</th>
                <th scope="col">Цена:</th>
                <th scope="col">Количество:</th>
                <th scope="col">Сумма:</th>
            </tr>
            </thead>
            <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.product.name_product }}</td>
                    <td>{{ item.product.price }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.product_sum }}</td>
                    <th scope="row">
                        <form action="{% url 'webapp:cart_delete' item.product_id %}" method="POST">
                            {% csrf_token %}
                            <a>
                                <button class="btn btn-danger" type="submit">Удалить</button>
                            </a>
                        </form>
                    </th>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>Итого:</td>
                <th scope="row">{{ total }}</th>
            </tr>
            </tfoot>
        </table>

        <a href="{% url 'webapp:index' %}" class="btn btn-primary">Назад</a>
        <br>
        <br>
        <h1>Оформить заказ</h1>
        <form action="{% url "webapp:order_create" %}" method="post">
            {% include 'partial/form.html' with button_text="Оформить" %}
        </form>
    </div>

{% endblock %}

templates/orders.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Заказы{% endblock %}
{% block nav %} {% endblock %}
{% block content %}
    <div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Название</th>
                <th scope="col">Цена</th>
                <th scope="col">Количество</th>
                <th scope="col">Сумма</th>
                <th scope="col">Время заказа</th>
            </tr>
            </thead>
            <tbody>
                {% for item in order_products%}
                    <tr>
                        <td>{{ item.product.name_goods }}</td>
                        <td>{{ item.product.price|floatformat:-2 }}</td>
                        <td>{{ item.amount }}</td>
                        <td>{{ item.product_sum}}</td>
                        <td>{{ item.order.created_at }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Search by name "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Records  {{ total_results }} found {{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for product in results %}
            <div class="card bg-light mb-3" style="max-width: 25rem;">
                <div class="card-header">{{ product.name_product }} ({{ product.price }})<span
                        style="padding: 0px 40px;">&nbsp;</span>
                    <a href="{% url 'update_product' product.pk %}">Редактировать</a>
                    <a href="{% url 'delete_product' product.pk %}">Удалить</a></div>
                <div class="card-body">
                    <p class="card-text">{{ product.descr_product }}</p>
                </div>
            </div>
        {% empty %}
            <p>Нет результатов.</p>
        {% endfor %}
        </button><a href="{% url "product_search" %}" class="btn btn-primary">Искать снова</a></button>
        </button><a href="{% url "index" %}" class="btn btn-primary">Назад</a></button>
    {% else %}
        <h1>Search by name</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Искать" class="btn btn-primary">
            </button><a href="{% url "index" %}" class="btn btn-primary">Назад</a></button>
        </form>
    {% endif %}
{% endblock %}